name: Build & Release PHP Extension

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'           # Trigger on tags like v1.0.0
  workflow_dispatch:

jobs:
  build-linux-macos:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: ['8.1', '8.2', '8.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpize

      - name: Build extension
        run: |
          phpize
          ./configure --enable-hello
          make
          mkdir -p output
          cp modules/*.so output/
          echo "; Enable hello extension" > output/hello.ini
          echo "extension=hello" >> output/hello.ini

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-${{ matrix.os }}-php${{ matrix.php }}
          path: output/*

  build-windows:
    strategy:
      matrix:
        arch: [x64, x86]
        ts: [nts, ts]
        php: ['8.1', '8.2', '8.3']
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Build extension (Windows)
        uses: php/php-windows-builder/extension@v1
        with:
          extension-url: https://github.com/mohan2020coder/hellophpext.git
          extension-ref: main
          php-version: ${{ matrix.php }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
          args: "--enable-hello"

      - name: Prepare ini and copy DLLs
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path output -Force | Out-Null
          Set-Content -Path output\hello.ini -Value "; Enable hello extension"
          Add-Content -Path output\hello.ini -Value "extension=hello"
          Write-Host "Listing DLL files under artifacts directory:"
          Get-ChildItem -Path artifacts -Recurse -Filter *.dll | ForEach-Object {
            Write-Host $_.FullName
          }
          Get-ChildItem -Path artifacts -Recurse -Filter *.dll | ForEach-Object {
            Copy-Item -Path $_.FullName -Destination output
          }
          Write-Host "DLL files copied to output folder:"
          Get-ChildItem -Path output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-windows-${{ matrix.arch }}-${{ matrix.ts }}-php${{ matrix.php }}
          path: output/*

  package-release:
    runs-on: ubuntu-latest
    needs: [build-linux-macos, build-windows]
    env:
      TAG_NAME: ${{ github.ref_name }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Organize artifacts by OS
        run: |
          mkdir -p release/linux release/macos release/windows
          for d in dist/*; do
            if [[ "$d" == *ubuntu* ]]; then
              cp -r "$d"/* release/linux/
            elif [[ "$d" == *macos* ]]; then
              cp -r "$d"/* release/macos/
            elif [[ "$d" == *windows* ]]; then
              cp -r "$d"/* release/windows/
            fi
          done

      - name: Create OS-specific ZIPs
        run: |
          echo "Creating hello-${TAG_NAME} OS-specific ZIP files"

          cd release
          for os in linux macos windows; do
            if [ -d "$os" ]; then
              zip -r ../hello-${os}-${TAG_NAME}.zip "$os"
            fi
          done
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: hello-*-${{ env.TAG_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
